### ISSUE TITLE
Convert degrees to directions

### ISSUE THREAD

**Issue by Bharath1910** [learn-hands-on/cli-weather-fetcher#1]
The dictionary we got from the API contains ``deg`` key, convert that degree to directions like North, South etc.

**Comment by Bharath1910** [comment]
@nallarahul any progress?

**Comment by nallarahul** [comment]
should i create a new file and do it ??

**Comment by Bharath1910** [comment]
completed the change, [PR](https://github.com/learn-hands-on/cli-weather-fetcher/pull/3)

**Comment by Bharath1910** [comment]
@nallarahul, 199 Test cases failed, try to reimplement the code and give PR once completed.
